<a href="https://colab.research.google.com/github/tassiogomes/MINDD-ISEP/blob/main/Another_copy_of_Project_v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

###### Installs

In [1]:
!pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.2.12-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from lazypredict) (8.1.7)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from lazypredict) (1.2.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from lazypredict) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from lazypredict) (4.66.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from lazypredict) (1.3.2)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.10/dist-packages (from lazypredict) (4.1.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (from lazypredict) (2.0.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from lightgbm->lazypredict) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from lightgbm->lazypredict) (1.11.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->lazypredict) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->lazypredict) (2023.3.post1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->lazypredict) (3.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->lazypredict) (1.16.0)
Installing collected packages: lazypredict
Successfully installed lazypredict-0.2.12

In [2]:
!pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.0-py3-none-any.whl (15.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 26.5 MB/s eta 0:00:00
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.5.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.23.5)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.7.1)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (4.66.1)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (1.11.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (3.1.2)
Requirement already satisfied: importlib-resources>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from sweetviz) (6.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.11.1->sweetviz) (2.1.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.44.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.16.0)
Installing collected packages: sweetviz
Successfully installed sweetviz-2.3.0

In [3]:
#Import Python Libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
import sweetviz as sv
import IPython
from lazypredict.Supervised import LazyClassifier

#Data exploration

#### Data Dictionary

|Column name| Description|
|----|---|
|ID| unique ID of representative|
|Loan Amount| loan amount applied|
|Funded Amount|loan amount funded|
|Funded Amount Investor| loan amount approved by the investors|
|Term| term of loan (in months)|
|Batch Enrolled| batch numbers to representatives|
|Interest Rate| interest rate (%) on loan|
|Grade| grade by the bank|
|Sub Grade| sub-grade by the bank|
|Employment Duration| duration|
|Home Ownership| Owner ship of home|
|Verification Status| Income verification by the bank|
|Payment Plan| if any payment plan has started against loan|
|Loan Title| loan title provided|
|Debit to Income| ratio of representative's total monthly debt repayment divided by self reported monthly income excluding mortgage|
|Delinquency - two years| number of 30+ days delinquency in past 2 years|
|Inquires - six months| total number of inquiries in last 6 months|
|Open Account| number of open credit line in representative's credit line|
|Public Record| number of derogatory public records|
|Revolving Balance| total credit revolving balance|
|Revolving Utilities| amount of credit a representative is using relative to revolving_balance|
|Total Accounts| total number of credit lines available in representatives credit line|
|Initial List Status| unique listing status of the loan - W(Waiting), F(Forwarded)|
|Total Received Interest| total interest received till date|
|Total Received Late Fee| total late fee received till date|
|Recoveries| post charge off gross recovery|
|Collection Recovery Fee| post charge off collection fee|
|Collection 12 months Medical| total collections in last 12 months excluding medical collections|
|Application Type| indicates when the representative is an individual or joint|
|Last week Pay| indicates how long (in weeks) a representative has paid EMI after batch enrolled|
|Accounts Delinquent| number of accounts on which the representative is delinquent|
|Total Collection Amount| total collection amount ever owed|
|Total Current Balance| total current balance from all accounts|
|Total Revolving Credit Limit| total revolving credit limit|
|Loan Status| 1 = Defaulter, 0 = Non Defaulters|

#### Tabular exploration

In [4]:
#Cargar datos
drive.mount('/content/drive')
df = pd.read_csv('drive/My Drive/MINDD/train.csv')
#df = pd.read_csv("/content/drive/MyDrive/train.csv")

Mounted at /content/drive

In [5]:
#drive.mount('/content/drive')
#df = pd.read_csv("/content/drive/MyDrive/train.csv")

In [6]:
df.columns

Index(['ID', 'Loan Amount', 'Funded Amount', 'Funded Amount Investor', 'Term',
       'Batch Enrolled', 'Interest Rate', 'Grade', 'Sub Grade',
       'Employment Duration', 'Home Ownership', 'Verification Status',
       'Payment Plan', 'Loan Title', 'Debit to Income',
       'Delinquency - two years', 'Inquires - six months', 'Open Account',
       'Public Record', 'Revolving Balance', 'Revolving Utilities',
       'Total Accounts', 'Initial List Status', 'Total Received Interest',
       'Total Received Late Fee', 'Recoveries', 'Collection Recovery Fee',
       'Collection 12 months Medical', 'Application Type', 'Last week Pay',
       'Accounts Delinquent', 'Total Collection Amount',
       'Total Current Balance', 'Total Revolving Credit Limit', 'Loan Status'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67463 entries, 0 to 67462
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   ID                            67463 non-null  int64
 1   Loan Amount                   67463 non-null  int64
 2   Funded Amount                 67463 non-null  int64
 3   Funded Amount Investor        67463 non-null  float64
 4   Term                          67463 non-null  int64
 5   Batch Enrolled                67463 non-null  object
 6   Interest Rate                 67463 non-null  float64
 7   Grade                         67463 non-null  object
 8   Sub Grade                     67463 non-null  object
 9   Employment Duration           67463 non-null  object
 10  Home Ownership                67463 non-null  float64
 11  Verification Status           67463 non-null  object
 12  Payment Plan                  67463 non-null  object
 13  Loan Title                    67463 non-null  object
 14  Debit to Income               67463 non-null  float64
 15  Delinquency - two years       67463 non-null  int64
 16  Inquires - six months         67463 non-null  int64
 17  Open Account                  67463 non-null  int64
 18  Public Record                 67463 non-null  int64
 19  Revolving Balance             67463 non-null  int64
 20  Revolving Utilities           67463 non-null  float64
 21  Total Accounts                67463 non-null  int64
 22  Initial List Status           67463 non-null  object
 23  Total Received Interest       67463 non-null  float64
 24  Total Received Late Fee       67463 non-null  float64
 25  Recoveries                    67463 non-null  float64
 26  Collection Recovery Fee       67463 non-null  float64
 27  Collection 12 months Medical  67463 non-null  int64
 28  Application Type              67463 non-null  object
 29  Last week Pay                 67463 non-null  int64
 30  Accounts Delinquent           67463 non-null  int64
 31  Total Collection Amount       67463 non-null  int64
 32  Total Current Balance         67463 non-null  int64
 33  Total Revolving Credit Limit  67463 non-null  int64
 34  Loan Status                   67463 non-null  int64
dtypes: float64(9), int64(17), object(9)
memory usage: 18.0+ MB

Vemos que no tiene valores nulos en ninguna de las columnas

In [8]:
df.drop_duplicates()

,ID,Loan Amount,Funded Amount,Funded Amount Investor,Term,Batch Enrolled,Interest Rate,Grade,Sub Grade,Employment Duration,...,Recoveries,Collection Recovery Fee,Collection 12 months Medical,Application Type,Last week Pay,Accounts Delinquent,Total Collection Amount,Total Current Balance,Total Revolving Credit Limit,Loan Status
0,65087372,10000,32236,12329.36,59,BAT2522922,11.14,B,C4,MORTGAGE,...,2.50,0.79,0,INDIVIDUAL,49,0,31,311301,6619,0
1,1450153,3609,11940,12192.00,59,BAT1586599,12.24,C,D3,RENT,...,2.38,0.97,0,INDIVIDUAL,109,0,53,182610,20885,0
2,1969101,28276,9311,21603.22,59,BAT2136391,12.55,F,D4,MORTGAGE,...,4.32,1.02,0,INDIVIDUAL,66,0,34,89801,26155,0
3,6651430,11170,6954,17877.16,59,BAT2428731,16.73,C,C3,MORTGAGE,...,0.11,0.75,0,INDIVIDUAL,39,0,40,9189,60214,0
4,14354669,16890,13226,13539.93,59,BAT5341619,15.01,C,D4,MORTGAGE,...,1294.82,0.37,0,INDIVIDUAL,18,0,430,126029,22579,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67458,16164945,13601,6848,13175.29,59,BAT3193689,9.41,C,A4,MORTGAGE,...,564.61,0.87,0,INDIVIDUAL,69,0,48,181775,34301,1
67459,35182714,8323,11046,15637.46,59,BAT1780517,9.97,C,B3,RENT,...,2.02,1.40,0,INDIVIDUAL,14,0,37,22692,8714,0
67460,16435904,15897,32921,12329.46,59,BAT1761981,19.65,A,F3,MORTGAGE,...,5.67,1.61,0,INDIVIDUAL,137,0,17,176857,42330,0
67461,5300325,16567,4975,21353.68,59,BAT2333412,13.17,D,E3,OWN,...,1.16,0.21,0,INDIVIDUAL,73,0,61,361339,39075,0
67462,65443173,15353,29875,14207.45,59,BAT1930365,16.03,B,D1,MORTGAGE,...,1.86,0.37,0,INDIVIDUAL,54,0,47,196960,66060,0

El dataset no contenia duplicados.

In [9]:
# Tassio
#check null values
df.isnull().sum(axis = 0)

ID                              0
Loan Amount                     0
Funded Amount                   0
Funded Amount Investor          0
Term                            0
Batch Enrolled                  0
Interest Rate                   0
Grade                           0
Sub Grade                       0
Employment Duration             0
Home Ownership                  0
Verification Status             0
Payment Plan                    0
Loan Title                      0
Debit to Income                 0
Delinquency - two years         0
Inquires - six months           0
Open Account                    0
Public Record                   0
Revolving Balance               0
Revolving Utilities             0
Total Accounts                  0
Initial List Status             0
Total Received Interest         0
Total Received Late Fee         0
Recoveries                      0
Collection Recovery Fee         0
Collection 12 months Medical    0
Application Type                0
Last week Pay                   0
Accounts Delinquent             0
Total Collection Amount         0
Total Current Balance           0
Total Revolving Credit Limit    0
Loan Status                     0
dtype: int64

No null values

In [10]:
# check if all ids are unique
len(df['ID'].unique()) == len(df.index)

True

In [11]:
def unique_value_for_dataframe(df):
  for cols in df.columns:
    print('----------Unique values in "'+ cols +'" column-------------------')
    print(df[cols].unique())
    print('-----------End of unique values for "' + cols +'" columns ---------------\n' )

unique_value_for_dataframe(df)

----------Unique values in "ID" column-------------------
[65087372  1450153  1969101 ... 16435904  5300325 65443173]
-----------End of unique values for "ID" columns ---------------

----------Unique values in "Loan Amount" column-------------------
[10000  3609 28276 ... 30703 17417  8323]
-----------End of unique values for "Loan Amount" columns ---------------

----------Unique values in "Funded Amount" column-------------------
[32236 11940  9311 ... 17672 32921 29875]
-----------End of unique values for "Funded Amount" columns ---------------

----------Unique values in "Funded Amount Investor" column-------------------
[12329.36286 12191.99692 21603.22455 ... 12329.45775 21353.68465
 14207.4486 ]
-----------End of unique values for "Funded Amount Investor" columns ---------------

----------Unique values in "Term" column-------------------
[59 36 58]
-----------End of unique values for "Term" columns ---------------

----------Unique values in "Batch Enrolled" column-------------------
['BAT2522922' 'BAT1586599' 'BAT2136391' 'BAT2428731' 'BAT5341619'
 'BAT4694572' 'BAT4808022' 'BAT2558388' 'BAT2078974' 'BAT2252229'
 'BAT2333412' 'BAT5849876' 'BAT2833642' 'BAT2803411' 'BAT5525466'
 'BAT5714674' 'BAT2003848' 'BAT4722912' 'BAT3873588' 'BAT1780517'
 'BAT4271519' 'BAT5811547' 'BAT1184694' 'BAT4136152' 'BAT3193689'
 'BAT1467036' 'BAT2575549' 'BAT4351734' 'BAT1104812' 'BAT5924421'
 'BAT1930365' 'BAT1766061' 'BAT5489674' 'BAT3865626' 'BAT5629144'
 'BAT5547201' 'BAT224923' 'BAT3726927' 'BAT3461431' 'BAT1761981'
 'BAT1135695']
-----------End of unique values for "Batch Enrolled" columns ---------------

----------Unique values in "Interest Rate" column-------------------
[11.13500686 12.23756263 12.54588365 ... 19.65094342 13.16909487
 16.03463076]
-----------End of unique values for "Interest Rate" columns ---------------

----------Unique values in "Grade" column-------------------
['B' 'C' 'F' 'A' 'G' 'E' 'D']
-----------End of unique values for "Grade" columns ---------------

----------Unique values in "Sub Grade" column-------------------
['C4' 'D3' 'D4' 'C3' 'G5' 'C5' 'A5' 'C2' 'B5' 'B1' 'B4' 'A4' 'B2' 'D2'
 'C1' 'F3' 'D1' 'F2' 'A2' 'A3' 'F1' 'E5' 'B3' 'F4' 'G1' 'F5' 'E1' 'E2'
 'D5' 'G2' 'E4' 'A1' 'G3' 'E3' 'G4']
-----------End of unique values for "Sub Grade" columns ---------------

----------Unique values in "Employment Duration" column-------------------
['MORTGAGE' 'RENT' 'OWN']
-----------End of unique values for "Employment Duration" columns ---------------

----------Unique values in "Home Ownership" column-------------------
[176346.6267   39833.921    91506.69105 ...  34813.96985  96938.83564
 105123.1558 ]
-----------End of unique values for "Home Ownership" columns ---------------

----------Unique values in "Verification Status" column-------------------
['Not Verified' 'Source Verified' 'Verified']
-----------End of unique values for "Verification Status" columns ---------------

----------Unique values in "Payment Plan" column-------------------
['n']
-----------End of unique values for "Payment Plan" columns ---------------

----------Unique values in "Loan Title" column-------------------
['Debt Consolidation' 'Debt consolidation' 'Credit card refinancing'
 'Home improvement' 'Credit Consolidation' 'Green loan' 'Other'
 'Moving and relocation' 'Credit Cards' 'Medical expenses'
 'DEBT CONSOLIDATION' 'Home Improvement' 'Refinance'
 'credit card consolidation' 'Lending Club' 'Debt Consolidation Loan'
 'Major purchase' 'Vacation' 'Business' 'Credit card payoff'
 'Credit Card Consolidation' 'credit card' 'Credit Card Refi'
 'Personal Loan' 'CC Refi' 'consolidate' 'Medical' 'Loan 1'
 'Consolidation' 'Card Consolidation' 'Car financing' 'debt'
 'home improvement' 'debt consolidation' 'Home buying' 'Freedom'
 'Consolidate' 'Consolidated' 'get out of debt' 'consolidation loan'
 'Dept consolidation' 'Personal loan' 'Personal' 'Debt' 'cards' 'Cards'
 'Bathroom' 'refi' 'Credit Card Loan' 'Credit Card Debt' 'House'
 'Debt Consolidation 2013' 'debt loan' 'CC Refinance' 'Consolidation Loan'
 'Home' 'CC consolidation' 'Credit Card' 'Credit Card Refinance'
 'Credit Loan' 'payoff' 'Bill Consolidation' 'credit card refinance'
 'Credit Card consolidation' 'Credit Card Paydown' 'Credit card pay off'
 'vacation' 'Credit card refinance' 'Get Debt Free' 'MYLOAN'
 'credit pay off' 'Payoff' 'consolidation' 'My Loan' 'Loan' 'Bill Payoff'
 'CC-Refinance' 'Debt Reduction' 'Medical loan' 'Wedding Loan' 'Credit'
 'CONSOLIDATE' 'personal' 'pay off bills' 'CC Consolidation'
 'Refinance Loan' 'Credit Card Payoff' 'Debt Payoff' 'Car Loan' 'Pay Off'
 'Debt Loan' 'CONSOLIDATION' 'Pool' 'Credit payoff'
 'Credit Card Refinance Loan' 'CC Loan' 'Debt Free'
 'debt consolidation loan' 'conso' 'Home Improvement Loan'
 'Loan Consolidation' 'Debt payoff' 'Lending loan' 'relief' 'CC' 'loan1'
 'Getting Ahead' 'Home loan' 'bills']
-----------End of unique values for "Loan Title" columns ---------------

----------Unique values in "Debit to Income" column-------------------
[16.28475781 15.41240945 28.13761862 ... 10.29577356  7.61462376
 16.05211225]
-----------End of unique values for "Debit to Income" columns ---------------

----------Unique values in "Delinquency - two years" column-------------------
[1 0 3 6 2 7 5 4 8]
-----------End of unique values for "Delinquency - two years" columns ---------------

----------Unique values in "Inquires - six months" column-------------------
[0 3 2 1 4 5]
-----------End of unique values for "Inquires - six months" columns ---------------

----------Unique values in "Open Account" column-------------------
[13 12 14  7 16 11  6 17 10  8  9 26 31 28 19 15 33 30 21 18 27 20 25 24
 23 22 34 32 29  5  4 36 35  3 37  2]
-----------End of unique values for "Open Account" columns ---------------

----------Unique values in "Public Record" column-------------------
[0 1 2 4 3]
-----------End of unique values for "Public Record" columns ---------------

----------Unique values in "Revolving Balance" column-------------------
[24246   812  1843 ... 18806 29762 27384]
-----------End of unique values for "Revolving Balance" columns ---------------

----------Unique values in "Revolving Utilities" column-------------------
[74.93255103 78.29718601  2.07303987 ...  1.50009028 68.4818825
 81.69232835]
-----------End of unique values for "Revolving Utilities" columns ---------------

----------Unique values in "Total Accounts" column-------------------
[ 7 13 20 12 22 37 33 17 30 46 21 19 10 16 14  9 25 11 24 23 15 18 28  8
 38 27 29  6 26  4  5 32 56 44 31 34 40 39 45 36 41 35 42 50 52 43 63 47
 66 48 49 54 68 53 55 65 51 60 61 59 57 64 72 58 71 67 69 70 62]
-----------End of unique values for "Total Accounts" columns ---------------

----------Unique values in "Initial List Status" column-------------------
['w' 'f']
-----------End of unique values for "Initial List Status" columns ---------------

----------Unique values in "Total Received Interest" column-------------------
[2929.646315   772.769385   863.3243956 ... 2691.995532  3659.334202
 1324.255922 ]
-----------End of unique values for "Total Received Interest" columns ---------------

----------Unique values in "Total Received Late Fee" column-------------------
[1.02055198e-01 3.61811700e-02 1.87786601e+01 ... 2.82115230e-02
 7.45083190e-02 6.70556000e-04]
-----------End of unique values for "Total Received Late Fee" columns ---------------

----------Unique values in "Recoveries" column-------------------
[2.49829096 2.37721476 4.31627734 ... 5.67309165 1.15745391 1.85647963]
-----------End of unique values for "Recoveries" columns ---------------

----------Unique values in "Collection Recovery Fee" column-------------------
[0.79372376 0.9748211  1.02007495 ... 1.60709263 0.20760821 0.3663859 ]
-----------End of unique values for "Collection Recovery Fee" columns ---------------

----------Unique values in "Collection 12 months Medical" column-------------------
[0 1]
-----------End of unique values for "Collection 12 months Medical" columns ---------------

----------Unique values in "Application Type" column-------------------
['INDIVIDUAL' 'JOINT']
-----------End of unique values for "Application Type" columns ---------------

----------Unique values in "Last week Pay" column-------------------
[ 49 109  66  39  18  32  71  87 144   9  34  55 120  72  83 126 128  76
 151  33  97  88 103   1  77   2  69  54  13   3  16 154  67  82  90  28
 139  98  50  14   6  42  65 118 157 161 137 155 122  57 152 131  51 119
  37 125  96   4  41 140  53 153  74  60  93 117 145  95 106  17  36 156
  22 130  64  43 110   8 101 138  59  91   0 147 159  21 123  61   7  40
  12  56 102 160 108  47  86  70  80  58  99  25  29 112 107 150 132  23
 149  19  85  63  27  73  38  31  44  92  89  94  45 133 104 127 115 113
 135 142  68  30 121 116 148   5  35  48  78 124  79  46  81  11 141 129
 143  52 105  20 114  62  15 146 134 111  10 100  84  26 158  24  75 136]
-----------End of unique values for "Last week Pay" columns ---------------

----------Unique values in "Accounts Delinquent" column-------------------
[0]
-----------End of unique values for "Accounts Delinquent" columns ---------------

----------Unique values in "Total Collection Amount" column-------------------
[  31   53   34 ... 9920 1902 5302]
-----------End of unique values for "Total Collection Amount" columns ---------------

----------Unique values in "Total Current Balance" column-------------------
[311301 182610  89801 ... 176857 361339 196960]
-----------End of unique values for "Total Current Balance" columns ---------------

----------Unique values in "Total Revolving Credit Limit" column-------------------
[ 6619 20885 26155 ... 42330 39075 66060]
-----------End of unique values for "Total Revolving Credit Limit" columns ---------------

----------Unique values in "Loan Status" column-------------------
[0 1]
-----------End of unique values for "Loan Status" columns ---------------

In [12]:
# shape
print(df.shape)
# describe
print(df.describe())

(67463, 35)
               ID  Loan Amount  Funded Amount  Funded Amount Investor  \
count    67463.00     67463.00       67463.00                67463.00
mean  25627607.75     16848.90       15770.60                14621.80
std   21091554.02      8367.87        8150.99                 6785.35
min    1297933.00      1014.00        1014.00                 1114.59
25%    6570288.00     10012.00        9266.50                 9831.68
50%   17915646.00     16073.00       13042.00                12793.68
75%   42715208.50     22106.00       21793.00                17807.59
max   72245779.00     35000.00       34999.00                34999.75

          Term  Interest Rate  Home Ownership  Debit to Income  \
count 67463.00       67463.00        67463.00         67463.00
mean     58.17          11.85        80541.50            23.30
std       3.33           3.72        45029.12             8.45
min      36.00           5.32        14573.54             0.68
25%      58.00           9.30        51689.84            16.76
50%      59.00          11.38        69335.83            22.66
75%      59.00          14.19        94623.32            30.05
max      59.00          27.18       406561.54            39.63

       Delinquency - two years  Inquires - six months  ...  \
count                 67463.00               67463.00  ...
mean                      0.33                   0.15  ...
std                       0.80                   0.47  ...
min                       0.00                   0.00  ...
25%                       0.00                   0.00  ...
50%                       0.00                   0.00  ...
75%                       0.00                   0.00  ...
max                       8.00                   5.00  ...

       Total Received Late Fee  Recoveries  Collection Recovery Fee  \
count                 67463.00    67463.00                 67463.00
mean                      1.14       59.69                     1.13
std                       5.24      357.03                     3.49
min                       0.00        0.00                     0.00
25%                       0.02        1.63                     0.48
50%                       0.04        3.34                     0.78
75%                       0.07        5.45                     1.07
max                      42.62     4354.47                   166.83

       Collection 12 months Medical  Last week Pay  Accounts Delinquent  \
count                      67463.00       67463.00             67463.00
mean                           0.02          71.16                 0.00
std                            0.14          43.32                 0.00
min                            0.00           0.00                 0.00
25%                            0.00          35.00                 0.00
50%                            0.00          68.00                 0.00
75%                            0.00         105.00                 0.00
max                            1.00         161.00                 0.00

       Total Collection Amount  Total Current Balance  \
count                 67463.00               67463.00
mean                    146.47              159573.93
std                     744.38              139033.25
min                       1.00                 617.00
25%                      24.00               50379.00
50%                      36.00              118369.00
75%                      46.00              228375.00
max                   16421.00             1177412.00

       Total Revolving Credit Limit  Loan Status
count                      67463.00     67463.00
mean                       23123.01         0.09
std                        20916.70         0.29
min                         1000.00         0.00
25%                         8155.50         0.00
50%                        16733.00         0.00
75%                        32146.50         0.00
max                       201169.00         1.00

[8 rows x 26 columns]

#### Autoreport

In [13]:
'''analyze_report = sv.analyze(df)
analyze_report.show_html('analyze.html', open_browser=False)

SyntaxError: ignored

In [ ]:
IPython.display.HTML('analyze.html')

#### Graphics exploration

In [ ]:
# Visualize the distribution of Loan Status
sns.countplot(x='Loan Status', data=df)
plt.title('Loan Status Distribution')
plt.show()

# Box plots to identify outliers
plt.figure(figsize=(6, 6))
sns.boxplot(x='Loan Status', y='Loan Amount', data=df)
plt.title('Loan Amount vs. Loan Status')
plt.show()

# Countplot for Grade
plt.figure(figsize=(8, 5))
sns.countplot(x='Grade', data=df, order=sorted(df['Grade'].unique()))
plt.title('Grade Distribution')
plt.show()

# Countplot for Verification Status
plt.figure(figsize=(8, 5))
sns.countplot(x='Verification Status', data=df)
plt.title('Verification Status Distribution')
plt.show()

# Histogram for Delinquency - two years
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Delinquency - two years', bins=30, kde=True)
plt.title('Distribution of Delinquency - two years')
plt.xlabel('Delinquency - two years')
plt.show()

# Histogram for Debit to Income
plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='Debit to Income', bins=30, kde=True)
plt.title('Distribution of Debit to Income')
plt.xlabel('Debit to Income')
plt.show()

#Data pre processing

##### Anova

In [14]:
from scipy.stats import f_oneway, chi2_contingency

# Separate the DataFrame into numerical and categorical attributes
numerical_attributes = df.select_dtypes(include=['int64', 'float64'])
categorical_attributes = df.select_dtypes(include=['object'])

# Create empty lists to store selected features for ANOVA
selected_features_anova = []

# Perform ANOVA for numerical attributes
for column in numerical_attributes.columns:
    p_value = f_oneway(df[df['Loan Status'] == 1][column], df[df['Loan Status'] == 0][column]).pvalue
    if p_value < 0.05:  # You can adjust the significance level (alpha) as needed
        selected_features_anova.append(column)

# Print the selected features for ANOVA
print("Selected features based on ANOVA:")
print(selected_features_anova)

# ANOVA results
anova_results = {}
for column in selected_features_anova:
    anova_result = f_oneway(df[df['Loan Status'] == 1][column], df[df['Loan Status'] == 0][column])
    anova_results[column] = anova_result.pvalue

# Print ANOVA results
print("ANOVA p-values for numerical attributes:")
print(anova_results)

Selected features based on ANOVA:
['Delinquency - two years', 'Public Record', 'Total Received Late Fee', 'Total Collection Amount', 'Total Current Balance', 'Loan Status']
ANOVA p-values for numerical attributes:
{'Delinquency - two years': 0.009462634922992178, 'Public Record': 0.005946386493849328, 'Total Received Late Fee': 0.014999219404735661, 'Total Collection Amount': 0.04037045067395023, 'Total Current Balance': 0.010689900265710124, 'Loan Status': 0.0}

##### chi-square

In [15]:
# Separate the DataFrame into numerical and categorical attributes
numerical_attributes = df.select_dtypes(include=['int64', 'float64'])
categorical_attributes = df.select_dtypes(include=['object'])

# Create empty lists to store selected features for ANOVA and Chi-Square
selected_features_chi2 = []

# Perform Chi-Square test for categorical attributes
for column in categorical_attributes.columns:
    contingency_table = pd.crosstab(df[column], df['Loan Status'])
    chi2, p_value, _, _ = chi2_contingency(contingency_table)
    if p_value < 0.05:
        selected_features_chi2.append(column)

# 2. Chi-Square for categorical attributes
chi2_results = {}
for column in selected_features_chi2:
    contingency_table = pd.crosstab(df[column], df['Loan Status'])
    chi2_result = chi2_contingency(contingency_table)
    chi2_results[column] = chi2_result[1]

# Print Chi-Square results
print("\nChi-Square p-values for categorical attributes:")
print(chi2_results)



print("\nSelected features based on Chi-Square:")
print(selected_features_chi2)

Chi-Square p-values for categorical attributes:
{'Grade': 0.0293605144624493, 'Employment Duration': 0.000318849414713897, 'Initial List Status': 0.0005038281525924869}

Selected features based on Chi-Square:
['Grade', 'Employment Duration', 'Initial List Status']

#####  Autocorrelation and multicollinearity

In [17]:
variables_anova = df[selected_features_anova]
variables_chi2 = df[selected_features_chi2]

# Concat two lists
selected_variables = pd.concat([variables_anova, variables_chi2], axis=1)

# Calculate the correlation matrix
correlation_matrix = selected_variables.corr()

# Correlation matrix
print("Matriz de Correlação:")
print(correlation_matrix)

Matriz de Correlação:
                         Delinquency - two years  Public Record  \
Delinquency - two years                     1.00           0.01
Public Record                               0.01           1.00
Total Received Late Fee                     0.01           0.02
Total Collection Amount                     0.01           0.01
Total Current Balance                       0.00           0.00
Loan Status                                 0.01           0.01

                         Total Received Late Fee  Total Collection Amount  \
Delinquency - two years                     0.01                     0.01
Public Record                               0.02                     0.01
Total Received Late Fee                     1.00                     0.01
Total Collection Amount                     0.01                     1.00
Total Current Balance                      -0.00                     0.01
Loan Status                                 0.01                     0.01

                         Total Current Balance  Loan Status
Delinquency - two years                   0.00         0.01
Public Record                             0.00         0.01
Total Received Late Fee                  -0.00         0.01
Total Collection Amount                   0.01         0.01
Total Current Balance                     1.00         0.01
Loan Status                               0.01         1.00

In [ ]:
# matriz de correlação
correlation_matrix = selected_variables.corr()

# valores próprios
eigenvalues = np.linalg.eigvals(correlation_matrix)

# Examinar os valores próprios
print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[1.04092074 0.98183245 0.98600066 0.99150041 0.99658361 1.00316213]

These results suggest that there is no significant multicollinearity between the variables selected by the ANOVA and Chi-square and eigenvalues test. Therefore, there is no impediment to proceed with the construction of predictive models using these variables.

#####  Oversampling

In [19]:
from sklearn.utils import resample

features_anova = ['Delinquency - two years', 'Public Record', 'Total Received Late Fee', 'Total Collection Amount', 'Total Current Balance', 'Loan Status']
features_chi2 = ['Grade', 'Employment Duration', 'Initial List Status']

# Criar DataFrame com as variáveis selecionadas
selected_features = df[features_anova + features_chi2]

# Separar as instâncias por classe
df_class_0 = selected_features[selected_features['Loan Status'] == 0]
df_class_1 = selected_features[selected_features['Loan Status'] == 1]

# Undersampling da classe majoritária
df_class_0_undersampled = resample(df_class_0, replace=False, n_samples=len(df_class_1), random_state=42)

# Concatenar os dataframes balanceados
df_balanced = pd.concat([df_class_0_undersampled, df_class_1])

# Embaralhar as instâncias para garantir aleatoriedade
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

In [21]:
# Contar a quantidade de instâncias para cada classe
count_loan_status = df_balanced['Loan Status'].value_counts()

# Calcular a porcentagem
percentage_loan_status = count_loan_status / len(df_balanced) * 100

# Exibir os resultados
print("Total de instâncias com Loan Status 0:", count_loan_status[0])
print("Total de instâncias com Loan Status 1:", count_loan_status[1])

print("\nPorcentagem de Loan Status 0: {:.2f}%".format(percentage_loan_status[0]))
print("Porcentagem de Loan Status 1: {:.2f}%".format(percentage_loan_status[1]))

Total de instâncias com Loan Status 0: 6241
Total de instâncias com Loan Status 1: 6241

Porcentagem de Loan Status 0: 50.00%
Porcentagem de Loan Status 1: 50.00%

In [23]:
df_balanced.tail()

,Delinquency - two years,Public Record,Total Received Late Fee,Total Collection Amount,Total Current Balance,Loan Status,Grade,Employment Duration,Initial List Status
12477,0,0,0.05,38,74817,1,F,RENT,w
12478,0,0,0.03,35,154863,0,C,RENT,w
12479,0,0,0.04,17,30131,0,A,MORTGAGE,f
12480,0,0,0.03,27,195884,0,B,MORTGAGE,f
12481,0,0,0.01,27,440078,1,G,MORTGAGE,w

##### Encode variables

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Assumindo que df_balanced é o DataFrame resultante do balanceamento e encoding anterior

# Separar variáveis preditoras (X) e variável alvo (y)
X = df_balanced.drop('Loan Status', axis=1)
y = df_balanced['Loan Status']

# Dividir dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Pré-processamento: normalizar numéricas e codificar categóricas
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), X.select_dtypes(include=['int64', 'float64']).columns),
        ('cat', OneHotEncoder(), X.select_dtypes(include=['object']).columns)
    ])

# Aplicar o pré-processamento aos dados de treino
X_train_preprocessed = preprocessor.fit_transform(X_train)

# Aplicar o pré-processamento aos dados de teste
X_test_preprocessed = preprocessor.transform(X_test)

In [25]:
# Contar a quantidade de instâncias para cada classe nos dados de treino
count_train_loan_status = y_train.value_counts()

# Calcular a porcentagem nos dados de treino
percentage_train_loan_status = count_train_loan_status / len(y_train) * 100

# Exibir os resultados nos dados de treino
print("Dados de Treino:")
print("Total de instâncias com Loan Status 0:", count_train_loan_status[0])
print("Total de instâncias com Loan Status 1:", count_train_loan_status[1])
print("Porcentagem de Loan Status 0 nos dados de treino: {:.2f}%".format(percentage_train_loan_status[0]))
print("Porcentagem de Loan Status 1 nos dados de treino: {:.2f}%\n".format(percentage_train_loan_status[1]))

# Contar a quantidade de instâncias para cada classe nos dados de teste
count_test_loan_status = y_test.value_counts()

# Calcular a porcentagem nos dados de teste
percentage_test_loan_status = count_test_loan_status / len(y_test) * 100

# Exibir os resultados nos dados de teste
print("Dados de Teste:")
print("Total de instâncias com Loan Status 0:", count_test_loan_status[0])
print("Total de instâncias com Loan Status 1:", count_test_loan_status[1])
print("Porcentagem de Loan Status 0 nos dados de teste: {:.2f}%".format(percentage_test_loan_status[0]))
print("Porcentagem de Loan Status 1 nos dados de teste: {:.2f}%".format(percentage_test_loan_status[1]))

Dados de Treino:
Total de instâncias com Loan Status 0: 4964
Total de instâncias com Loan Status 1: 5021
Porcentagem de Loan Status 0 nos dados de treino: 49.71%
Porcentagem de Loan Status 1 nos dados de treino: 50.29%

Dados de Teste:
Total de instâncias com Loan Status 0: 1277
Total de instâncias com Loan Status 1: 1220
Porcentagem de Loan Status 0 nos dados de teste: 51.14%
Porcentagem de Loan Status 1 nos dados de teste: 48.86%

# Models

In [26]:
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# 1. Naive Bayes
naive_bayes_classifier = GaussianNB()
naive_bayes_classifier.fit(X_train_preprocessed, y_train)
y_pred_naive_bayes = naive_bayes_classifier.predict(X_test_preprocessed)

# Métricas para Naive Bayes
accuracy_naive_bayes = accuracy_score(y_test, y_pred_naive_bayes)
precision_naive_bayes = precision_score(y_test, y_pred_naive_bayes)
recall_naive_bayes = recall_score(y_test, y_pred_naive_bayes)
f1_naive_bayes = f1_score(y_test, y_pred_naive_bayes)

# Exibir resultados para Naive Bayes
print("Resultados para Naive Bayes:")
print("Acurácia:", accuracy_naive_bayes)
print("Precisão:", precision_naive_bayes)
print("Recall:", recall_naive_bayes)
print("F1 Score:", f1_naive_bayes)
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_naive_bayes))

# 2. K-Nearest Neighbors (KNN)
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_preprocessed, y_train)
y_pred_knn = knn_classifier.predict(X_test_preprocessed)

# Métricas para KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn)
recall_knn = recall_score(y_test, y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)

# Exibir resultados para KNN
print("\nResultados para K-Nearest Neighbors (KNN):")
print("Acurácia:", accuracy_knn)
print("Precisão:", precision_knn)
print("Recall:", recall_knn)
print("F1 Score:", f1_knn)
print("\nRelatório de Classificação:")
print(classification_report(y_test, y_pred_knn))

Resultados para Naive Bayes:
Acurácia: 0.5234281137364838
Precisão: 0.5297619047619048
Recall: 0.21885245901639344
F1 Score: 0.30974477958236657

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.52      0.81      0.64      1277
           1       0.53      0.22      0.31      1220

    accuracy                           0.52      2497
   macro avg       0.53      0.52      0.47      2497
weighted avg       0.53      0.52      0.48      2497


Resultados para K-Nearest Neighbors (KNN):
Acurácia: 0.500200240288346
Precisão: 0.4886731391585761
Recall: 0.49508196721311476
F1 Score: 0.49185667752442996

Relatório de Classificação:
              precision    recall  f1-score   support

           0       0.51      0.51      0.51      1277
           1       0.49      0.50      0.49      1220

    accuracy                           0.50      2497
   macro avg       0.50      0.50      0.50      2497
weighted avg       0.50      0.50      0.50      2497